name: Build and Deploy React App

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Initialize Submodule
      run: |
        git submodule init
        git submodule update --recursive --remote

  #git config --global url."https://${{ secrets.SUBMODULE_TOKEN }}@github.com/".insteadOf "https://github.com/"
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: npm ci
      working-directory: ./react-resume

    - name: Build React App
      run: npm run build
      working-directory: ./react-resume
    
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2.0.0
      with:
        path: ./react-resume/dist/

#    - name: Test React App
#      run: npm run test
#      working-directory: ./react-resume

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.9
      #with:
        # GitHub token
        #token: # default is ${{ github.token }}
          
      

